ChartDataSet:
  type: object
  properties:
    label:
      type: string
      format: string
      example: "Checking account"
      description: "This is the title of the current set. It can refer to an account, a budget or another object (by name)."
    currency_id:
      type: string
      format: string
      example: "5"
      description: "The currency ID of the currency associated to the data in the entries."
    currency_code:
      type: string
      format: string
      example: "EUR"
    currency_symbol:
      type: string
      format: string
      example: "$"
    currency_decimal_places:
      type: integer
      format: int32
      example: 2
      description: "Number of decimals for the currency associated to the data in the entries."
    type:
      type: string
      format: string
      example: "line"
      description: "Indicated the type of chart that is expected to be rendered. You can safely ignore this if you want."
    yAxisID: 
      type: integer
      format: int32
      example: 0
      description: "Used to indicate the Y axis for this data set. Is usually between 0 and 1 (left and right side of the chart)."
    entries:
      type: object
      description: "The actual entries for this data set. They 'key' value is the label for the data point. The value is the actual (numerical) value."
      items:
        $ref: '#/components/schemas/ChartDataPoint'