/chart/category/overview:
  get:
    tags:
      - charts
    summary: Dashboard chart with category information.
    description: |
      This endpoint returns the data required to generate a chart with basic category information.
    operationId: getChartCategoryOverview
    parameters:
      _tpl_correlationParameter,3:
      _tpl_mandatoryDateRangeParameters,3:
    responses:
      _tpl_unauthenticatedResponse,3:
      _tpl_notFoundResponse,3:
      _tpl_badRequestResponse,3:
      _tpl_validationErrorResponse,3:
      _tpl_internalExceptionResponse,3:
      "200":
        description: Line chart oriented chart information. Check out the model for more details. Each entry is a line (or bar) in the chart.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartLine'
